apiVersion: batch/v1
kind: Job
metadata:
  name: minigo-cc-evaluator-$MODEL_WHITE_NUM-$MODEL_BLACK_NUM
spec:
  parallelism: 10
  completions: 10
  template:
    metadata:
      name: gpu-evaluator
    spec:
      containers:
      - name: evaluator
        image: gcr.io/$PROJECT/minigo-cc-evaluator:$VERSION_TAG
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: service-credentials
          mountPath: /etc/credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/service-account.json
        - name: SGF_BUCKET_NAME
          value: tensor-go-minigo-cross-evals
        - name: MODEL_WHITE
          value: $MODEL_WHITE
        - name: MODEL_BLACK
          value: $MODEL_BLACK
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      volumes:
      - name: service-credentials
        secret:
          secretName: $SERVICE_ACCOUNT-creds
      restartPolicy: OnFailure
